// ---------------------------------------------------------
// This file was generated by parol.
// It is not intended for manual editing and changes will be
// lost after next build.
// ---------------------------------------------------------

use parol_runtime::once_cell::sync::Lazy;
use parol_runtime::parser::parse_tree_type::TreeConstruct;
#[allow(unused_imports)]
use parol_runtime::parser::{LLKParser, LookaheadDFA, ParseType, Production, Trans};
use parol_runtime::{ParolError, ParseTree, TerminalIndex};
use parol_runtime::{ScannerConfig, TokenStream, Tokenizer};
use std::path::Path;

use crate::grammar::Grammar;
use crate::grammar_trait::GrammarAuto;

use parol_runtime::lexer::tokenizer::{
    ERROR_TOKEN, NEW_LINE_TOKEN, UNMATCHABLE_TOKEN, WHITESPACE_TOKEN,
};

pub const TERMINALS: &[(&str, Option<(bool, &str)>); 34] = &[
    /*  0 */ (UNMATCHABLE_TOKEN, None),
    /*  1 */ (UNMATCHABLE_TOKEN, None),
    /*  2 */ (UNMATCHABLE_TOKEN, None),
    /*  3 */ (UNMATCHABLE_TOKEN, None),
    /*  4 */ (UNMATCHABLE_TOKEN, None),
    /*  5 */ (r"\d[\d_]*", None),
    /*  6 */ (r"true", None),
    /*  7 */ (r"false", None),
    /*  8 */ (r"null", None),
    /*  9 */ (r"!", None),
    /* 10 */ (r#"""#, None),
    /* 11 */ (r#"[a-zA-Z0-9-_]+""#, None),
    /* 12 */ (r#"(\\[nrt\\"0]|[^\\"\r\n])*"#, None),
    /* 13 */ (r#"[^\\"\r\n]*"#, None),
    /* 14 */ (r"[a-zA-Z0-9-_]+`([^`\r\n]|\\`)*`", None),
    /* 15 */ (r"`([^`\r\n]|\\`)*`", None),
    /* 16 */ (r"\r\n|\r|\n", None),
    /* 17 */ (r"[\s--\r\n]+", None),
    /* 18 */ (r"@", None),
    /* 19 */ (r"\$", None),
    /* 20 */ (r"\.", None),
    /* 21 */ (r"\{", None),
    /* 22 */ (r"\}", None),
    /* 23 */ (r"\[", None),
    /* 24 */ (r"\]", None),
    /* 25 */ (r"=", None),
    /* 26 */ (r",", None),
    /* 27 */ (r"\\\\", None),
    /* 28 */ (r":", None),
    /* 29 */ (r"[a-zA-Z_\-0-9]+", None),
    /* 30 */ (r"```[a-zA-Z0-9-_]+", None),
    /* 31 */ (r"```", None),
    /* 32 */ (r"[^\n]*", None),
    /* 33 */ (ERROR_TOKEN, None),
];

pub const TERMINAL_NAMES: &[&str; 34] = &[
    /*  0 */ "EndOfInput",
    /*  1 */ "Newline",
    /*  2 */ "Whitespace",
    /*  3 */ "LineComment",
    /*  4 */ "BlockComment",
    /*  5 */ "Integer",
    /*  6 */ "True",
    /*  7 */ "False",
    /*  8 */ "Null",
    /*  9 */ "Hole",
    /* 10 */ "Quote",
    /* 11 */ "TypedQuote",
    /* 12 */ "InStr",
    /* 13 */ "Text",
    /* 14 */ "NamedCode",
    /* 15 */ "Code",
    /* 16 */ "Newline0",
    /* 17 */ "Ws",
    /* 18 */ "At",
    /* 19 */ "Ext",
    /* 20 */ "Dot",
    /* 21 */ "Begin",
    /* 22 */ "End",
    /* 23 */ "ArrayBegin",
    /* 24 */ "ArrayEnd",
    /* 25 */ "Bind",
    /* 26 */ "Comma",
    /* 27 */ "Continue",
    /* 28 */ "TextStart",
    /* 29 */ "Ident",
    /* 30 */ "NamedCodeBlockBegin",
    /* 31 */ "CodeBlockDelimiter",
    /* 32 */ "CodeBlockLine",
    /* 33 */ "Error",
];

/* SCANNER_0: "INITIAL" */
const SCANNER_0: (&[&str; 5], &[TerminalIndex; 23]) = (
    &[
        /*  0 */ UNMATCHABLE_TOKEN,
        /*  1 */ NEW_LINE_TOKEN,
        /*  2 */ WHITESPACE_TOKEN,
        /*  3 */ r"#.*(\r\n|\r|\n)?",
        /*  4 */ UNMATCHABLE_TOKEN,
    ],
    &[
        5,  /* Integer */
        6,  /* True */
        7,  /* False */
        8,  /* Null */
        9,  /* Hole */
        10, /* Quote */
        11, /* TypedQuote */
        14, /* NamedCode */
        15, /* Code */
        18, /* At */
        19, /* Ext */
        20, /* Dot */
        21, /* Begin */
        22, /* End */
        23, /* ArrayBegin */
        24, /* ArrayEnd */
        25, /* Bind */
        26, /* Comma */
        27, /* Continue */
        28, /* TextStart */
        29, /* Ident */
        30, /* NamedCodeBlockBegin */
        31, /* CodeBlockDelimiter */
    ],
);

/* SCANNER_1: "Str" */
const SCANNER_1: (&[&str; 5], &[TerminalIndex; 3]) = (
    &[
        /*  0 */ UNMATCHABLE_TOKEN,
        /*  1 */ UNMATCHABLE_TOKEN,
        /*  2 */ UNMATCHABLE_TOKEN,
        /*  3 */ UNMATCHABLE_TOKEN,
        /*  4 */ UNMATCHABLE_TOKEN,
    ],
    &[10 /* Quote */, 12 /* InStr */, 17 /* Ws */],
);

/* SCANNER_2: "CodeBlockState" */
const SCANNER_2: (&[&str; 5], &[TerminalIndex; 4]) = (
    &[
        /*  0 */ UNMATCHABLE_TOKEN,
        /*  1 */ UNMATCHABLE_TOKEN,
        /*  2 */ UNMATCHABLE_TOKEN,
        /*  3 */ UNMATCHABLE_TOKEN,
        /*  4 */ UNMATCHABLE_TOKEN,
    ],
    &[
        16, /* Newline0 */
        17, /* Ws */
        31, /* CodeBlockDelimiter */
        32, /* CodeBlockLine */
    ],
);

/* SCANNER_3: "Text" */
const SCANNER_3: (&[&str; 5], &[TerminalIndex; 3]) = (
    &[
        /*  0 */ UNMATCHABLE_TOKEN,
        /*  1 */ UNMATCHABLE_TOKEN,
        /*  2 */ UNMATCHABLE_TOKEN,
        /*  3 */ UNMATCHABLE_TOKEN,
        /*  4 */ UNMATCHABLE_TOKEN,
    ],
    &[13 /* Text */, 16 /* Newline0 */, 17 /* Ws */],
);

const MAX_K: usize = 1;

pub const NON_TERMINALS: &[&str; 64] = &[
    /*  0 */ "Array",
    /*  1 */ "ArrayBegin",
    /*  2 */ "ArrayEnd",
    /*  3 */ "ArrayList",
    /*  4 */ "ArrayMarker",
    /*  5 */ "ArrayMarkerOpt",
    /*  6 */ "ArrayOpt",
    /*  7 */ "At",
    /*  8 */ "Begin",
    /*  9 */ "Bind",
    /* 10 */ "Binding",
    /* 11 */ "Bindings",
    /* 12 */ "Boolean",
    /* 13 */ "Code",
    /* 14 */ "CodeBlock",
    /* 15 */ "CodeBlockDelimiter",
    /* 16 */ "CodeBlockLine",
    /* 17 */ "CodeBlockTailCommon",
    /* 18 */ "CodeBlockTailCommonList",
    /* 19 */ "CodeBlockTailCommonOpt",
    /* 20 */ "Comma",
    /* 21 */ "Continue",
    /* 22 */ "Dot",
    /* 23 */ "End",
    /* 24 */ "Ext",
    /* 25 */ "ExtensionNameSpace",
    /* 26 */ "False",
    /* 27 */ "Hole",
    /* 28 */ "Ident",
    /* 29 */ "InStr",
    /* 30 */ "Integer",
    /* 31 */ "Key",
    /* 32 */ "KeyBase",
    /* 33 */ "KeyOpt",
    /* 34 */ "Keys",
    /* 35 */ "KeysList",
    /* 36 */ "NamedCode",
    /* 37 */ "NamedCodeBlock",
    /* 38 */ "NamedCodeBlockBegin",
    /* 39 */ "Newline",
    /* 40 */ "Null",
    /* 41 */ "Object",
    /* 42 */ "ObjectList",
    /* 43 */ "ObjectOpt",
    /* 44 */ "Quote",
    /* 45 */ "Section",
    /* 46 */ "SectionBinding",
    /* 47 */ "SectionList",
    /* 48 */ "Str",
    /* 49 */ "StrContinues",
    /* 50 */ "StrContinuesList",
    /* 51 */ "Swon",
    /* 52 */ "SwonList",
    /* 53 */ "SwonList0",
    /* 54 */ "Text",
    /* 55 */ "TextBinding",
    /* 56 */ "TextBindingOpt",
    /* 57 */ "TextStart",
    /* 58 */ "True",
    /* 59 */ "TypedQuote",
    /* 60 */ "TypedStr",
    /* 61 */ "Value",
    /* 62 */ "ValueBinding",
    /* 63 */ "Ws",
];

pub const LOOKAHEAD_AUTOMATA: &[LookaheadDFA; 64] = &[
    /* 0 - "Array" */
    LookaheadDFA {
        prod0: 48,
        transitions: &[],
        k: 0,
    },
    /* 1 - "ArrayBegin" */
    LookaheadDFA {
        prod0: 85,
        transitions: &[],
        k: 0,
    },
    /* 2 - "ArrayEnd" */
    LookaheadDFA {
        prod0: 86,
        transitions: &[],
        k: 0,
    },
    /* 3 - "ArrayList" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 5, 1, 49),
            Trans(0, 6, 1, 49),
            Trans(0, 7, 1, 49),
            Trans(0, 8, 1, 49),
            Trans(0, 9, 1, 49),
            Trans(0, 10, 1, 49),
            Trans(0, 11, 1, 49),
            Trans(0, 14, 1, 49),
            Trans(0, 15, 1, 49),
            Trans(0, 21, 1, 49),
            Trans(0, 23, 1, 49),
            Trans(0, 24, 2, 50),
            Trans(0, 30, 1, 49),
            Trans(0, 31, 1, 49),
        ],
        k: 1,
    },
    /* 4 - "ArrayMarker" */
    LookaheadDFA {
        prod0: 23,
        transitions: &[],
        k: 0,
    },
    /* 5 - "ArrayMarkerOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 5, 1, 24), Trans(0, 24, 2, 25)],
        k: 1,
    },
    /* 6 - "ArrayOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 5, 2, 52),
            Trans(0, 6, 2, 52),
            Trans(0, 7, 2, 52),
            Trans(0, 8, 2, 52),
            Trans(0, 9, 2, 52),
            Trans(0, 10, 2, 52),
            Trans(0, 11, 2, 52),
            Trans(0, 14, 2, 52),
            Trans(0, 15, 2, 52),
            Trans(0, 21, 2, 52),
            Trans(0, 23, 2, 52),
            Trans(0, 24, 2, 52),
            Trans(0, 26, 1, 51),
            Trans(0, 30, 2, 52),
            Trans(0, 31, 2, 52),
        ],
        k: 1,
    },
    /* 7 - "At" */
    LookaheadDFA {
        prod0: 80,
        transitions: &[],
        k: 0,
    },
    /* 8 - "Begin" */
    LookaheadDFA {
        prod0: 83,
        transitions: &[],
        k: 0,
    },
    /* 9 - "Bind" */
    LookaheadDFA {
        prod0: 87,
        transitions: &[],
        k: 0,
    },
    /* 10 - "Binding" */
    LookaheadDFA {
        prod0: 5,
        transitions: &[],
        k: 0,
    },
    /* 11 - "Bindings" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 21, 2, 7), Trans(0, 25, 1, 6), Trans(0, 28, 3, 8)],
        k: 1,
    },
    /* 12 - "Boolean" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 6, 1, 54), Trans(0, 7, 2, 55)],
        k: 1,
    },
    /* 13 - "Code" */
    LookaheadDFA {
        prod0: 77,
        transitions: &[],
        k: 0,
    },
    /* 14 - "CodeBlock" */
    LookaheadDFA {
        prod0: 70,
        transitions: &[],
        k: 0,
    },
    /* 15 - "CodeBlockDelimiter" */
    LookaheadDFA {
        prod0: 93,
        transitions: &[],
        k: 0,
    },
    /* 16 - "CodeBlockLine" */
    LookaheadDFA {
        prod0: 94,
        transitions: &[],
        k: 0,
    },
    /* 17 - "CodeBlockTailCommon" */
    LookaheadDFA {
        prod0: 71,
        transitions: &[],
        k: 0,
    },
    /* 18 - "CodeBlockTailCommonList" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 17, 2, 73),
            Trans(0, 31, 2, 73),
            Trans(0, 32, 1, 72),
        ],
        k: 1,
    },
    /* 19 - "CodeBlockTailCommonOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 17, 1, 74), Trans(0, 31, 2, 75)],
        k: 1,
    },
    /* 20 - "Comma" */
    LookaheadDFA {
        prod0: 88,
        transitions: &[],
        k: 0,
    },
    /* 21 - "Continue" */
    LookaheadDFA {
        prod0: 89,
        transitions: &[],
        k: 0,
    },
    /* 22 - "Dot" */
    LookaheadDFA {
        prod0: 82,
        transitions: &[],
        k: 0,
    },
    /* 23 - "End" */
    LookaheadDFA {
        prod0: 84,
        transitions: &[],
        k: 0,
    },
    /* 24 - "Ext" */
    LookaheadDFA {
        prod0: 81,
        transitions: &[],
        k: 0,
    },
    /* 25 - "ExtensionNameSpace" */
    LookaheadDFA {
        prod0: 30,
        transitions: &[],
        k: 0,
    },
    /* 26 - "False" */
    LookaheadDFA {
        prod0: 57,
        transitions: &[],
        k: 0,
    },
    /* 27 - "Hole" */
    LookaheadDFA {
        prod0: 59,
        transitions: &[],
        k: 0,
    },
    /* 28 - "Ident" */
    LookaheadDFA {
        prod0: 91,
        transitions: &[],
        k: 0,
    },
    /* 29 - "InStr" */
    LookaheadDFA {
        prod0: 67,
        transitions: &[],
        k: 0,
    },
    /* 30 - "Integer" */
    LookaheadDFA {
        prod0: 53,
        transitions: &[],
        k: 0,
    },
    /* 31 - "Key" */
    LookaheadDFA {
        prod0: 20,
        transitions: &[],
        k: 0,
    },
    /* 32 - "KeyBase" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 5, 4, 29),
            Trans(0, 10, 3, 28),
            Trans(0, 19, 2, 27),
            Trans(0, 29, 1, 26),
        ],
        k: 1,
    },
    /* 33 - "KeyOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 0, 2, 22),
            Trans(0, 5, 2, 22),
            Trans(0, 10, 2, 22),
            Trans(0, 18, 2, 22),
            Trans(0, 19, 2, 22),
            Trans(0, 20, 2, 22),
            Trans(0, 21, 2, 22),
            Trans(0, 22, 2, 22),
            Trans(0, 23, 1, 21),
            Trans(0, 25, 2, 22),
            Trans(0, 28, 2, 22),
            Trans(0, 29, 2, 22),
        ],
        k: 1,
    },
    /* 34 - "Keys" */
    LookaheadDFA {
        prod0: 17,
        transitions: &[],
        k: 0,
    },
    /* 35 - "KeysList" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 0, 2, 19),
            Trans(0, 5, 2, 19),
            Trans(0, 10, 2, 19),
            Trans(0, 18, 2, 19),
            Trans(0, 19, 2, 19),
            Trans(0, 20, 1, 18),
            Trans(0, 21, 2, 19),
            Trans(0, 22, 2, 19),
            Trans(0, 25, 2, 19),
            Trans(0, 28, 2, 19),
            Trans(0, 29, 2, 19),
        ],
        k: 1,
    },
    /* 36 - "NamedCode" */
    LookaheadDFA {
        prod0: 76,
        transitions: &[],
        k: 0,
    },
    /* 37 - "NamedCodeBlock" */
    LookaheadDFA {
        prod0: 69,
        transitions: &[],
        k: 0,
    },
    /* 38 - "NamedCodeBlockBegin" */
    LookaheadDFA {
        prod0: 92,
        transitions: &[],
        k: 0,
    },
    /* 39 - "Newline" */
    LookaheadDFA {
        prod0: 78,
        transitions: &[],
        k: 0,
    },
    /* 40 - "Null" */
    LookaheadDFA {
        prod0: 58,
        transitions: &[],
        k: 0,
    },
    /* 41 - "Object" */
    LookaheadDFA {
        prod0: 43,
        transitions: &[],
        k: 0,
    },
    /* 42 - "ObjectList" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 5, 1, 44),
            Trans(0, 10, 1, 44),
            Trans(0, 19, 1, 44),
            Trans(0, 22, 2, 45),
            Trans(0, 29, 1, 44),
        ],
        k: 1,
    },
    /* 43 - "ObjectOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 5, 2, 47),
            Trans(0, 10, 2, 47),
            Trans(0, 19, 2, 47),
            Trans(0, 22, 2, 47),
            Trans(0, 26, 1, 46),
            Trans(0, 29, 2, 47),
        ],
        k: 1,
    },
    /* 44 - "Quote" */
    LookaheadDFA {
        prod0: 65,
        transitions: &[],
        k: 0,
    },
    /* 45 - "Section" */
    LookaheadDFA {
        prod0: 14,
        transitions: &[],
        k: 0,
    },
    /* 46 - "SectionBinding" */
    LookaheadDFA {
        prod0: 10,
        transitions: &[],
        k: 0,
    },
    /* 47 - "SectionList" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 0, 2, 16),
            Trans(0, 5, 1, 15),
            Trans(0, 10, 1, 15),
            Trans(0, 18, 2, 16),
            Trans(0, 19, 1, 15),
            Trans(0, 22, 2, 16),
            Trans(0, 29, 1, 15),
        ],
        k: 1,
    },
    /* 48 - "Str" */
    LookaheadDFA {
        prod0: 63,
        transitions: &[],
        k: 0,
    },
    /* 49 - "StrContinues" */
    LookaheadDFA {
        prod0: 60,
        transitions: &[],
        k: 0,
    },
    /* 50 - "StrContinuesList" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 0, 2, 62),
            Trans(0, 5, 2, 62),
            Trans(0, 6, 2, 62),
            Trans(0, 7, 2, 62),
            Trans(0, 8, 2, 62),
            Trans(0, 9, 2, 62),
            Trans(0, 10, 2, 62),
            Trans(0, 11, 2, 62),
            Trans(0, 14, 2, 62),
            Trans(0, 15, 2, 62),
            Trans(0, 18, 2, 62),
            Trans(0, 19, 2, 62),
            Trans(0, 21, 2, 62),
            Trans(0, 22, 2, 62),
            Trans(0, 23, 2, 62),
            Trans(0, 24, 2, 62),
            Trans(0, 26, 2, 62),
            Trans(0, 27, 1, 61),
            Trans(0, 29, 2, 62),
            Trans(0, 30, 2, 62),
            Trans(0, 31, 2, 62),
        ],
        k: 1,
    },
    /* 51 - "Swon" */
    LookaheadDFA {
        prod0: 0,
        transitions: &[],
        k: 0,
    },
    /* 52 - "SwonList" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 0, 2, 4),
            Trans(0, 5, 1, 3),
            Trans(0, 10, 1, 3),
            Trans(0, 18, 2, 4),
            Trans(0, 19, 1, 3),
            Trans(0, 22, 2, 4),
            Trans(0, 29, 1, 3),
        ],
        k: 1,
    },
    /* 53 - "SwonList0" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 0, 2, 2), Trans(0, 18, 1, 1), Trans(0, 22, 2, 2)],
        k: 1,
    },
    /* 54 - "Text" */
    LookaheadDFA {
        prod0: 68,
        transitions: &[],
        k: 0,
    },
    /* 55 - "TextBinding" */
    LookaheadDFA {
        prod0: 11,
        transitions: &[],
        k: 0,
    },
    /* 56 - "TextBindingOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 13, 2, 13), Trans(0, 17, 1, 12)],
        k: 1,
    },
    /* 57 - "TextStart" */
    LookaheadDFA {
        prod0: 90,
        transitions: &[],
        k: 0,
    },
    /* 58 - "True" */
    LookaheadDFA {
        prod0: 56,
        transitions: &[],
        k: 0,
    },
    /* 59 - "TypedQuote" */
    LookaheadDFA {
        prod0: 66,
        transitions: &[],
        k: 0,
    },
    /* 60 - "TypedStr" */
    LookaheadDFA {
        prod0: 64,
        transitions: &[],
        k: 0,
    },
    /* 61 - "Value" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 5, 3, 33),
            Trans(0, 6, 4, 34),
            Trans(0, 7, 4, 34),
            Trans(0, 8, 5, 35),
            Trans(0, 9, 8, 38),
            Trans(0, 10, 6, 36),
            Trans(0, 11, 7, 37),
            Trans(0, 14, 11, 41),
            Trans(0, 15, 12, 42),
            Trans(0, 21, 1, 31),
            Trans(0, 23, 2, 32),
            Trans(0, 30, 9, 39),
            Trans(0, 31, 10, 40),
        ],
        k: 1,
    },
    /* 62 - "ValueBinding" */
    LookaheadDFA {
        prod0: 9,
        transitions: &[],
        k: 0,
    },
    /* 63 - "Ws" */
    LookaheadDFA {
        prod0: 79,
        transitions: &[],
        k: 0,
    },
];

pub const PRODUCTIONS: &[Production; 95] = &[
    // 0 - Swon: SwonList /* Vec */ SwonList0 /* Vec */;
    Production {
        lhs: 51,
        production: &[ParseType::N(53), ParseType::N(52)],
    },
    // 1 - SwonList0: Section SwonList0;
    Production {
        lhs: 53,
        production: &[ParseType::N(53), ParseType::N(45)],
    },
    // 2 - SwonList0: ;
    Production {
        lhs: 53,
        production: &[],
    },
    // 3 - SwonList: Binding SwonList;
    Production {
        lhs: 52,
        production: &[ParseType::N(52), ParseType::N(10)],
    },
    // 4 - SwonList: ;
    Production {
        lhs: 52,
        production: &[],
    },
    // 5 - Binding: Keys Bindings;
    Production {
        lhs: 10,
        production: &[ParseType::N(11), ParseType::N(34)],
    },
    // 6 - Bindings: ValueBinding;
    Production {
        lhs: 11,
        production: &[ParseType::N(62)],
    },
    // 7 - Bindings: SectionBinding;
    Production {
        lhs: 11,
        production: &[ParseType::N(46)],
    },
    // 8 - Bindings: TextBinding;
    Production {
        lhs: 11,
        production: &[ParseType::N(55)],
    },
    // 9 - ValueBinding: Bind Value;
    Production {
        lhs: 62,
        production: &[ParseType::N(61), ParseType::N(9)],
    },
    // 10 - SectionBinding: Begin Swon End;
    Production {
        lhs: 46,
        production: &[ParseType::N(23), ParseType::N(51), ParseType::N(8)],
    },
    // 11 - TextBinding: TextStart TextBindingOpt /* Option */ Text Newline;
    Production {
        lhs: 55,
        production: &[
            ParseType::N(39),
            ParseType::N(54),
            ParseType::N(56),
            ParseType::N(57),
        ],
    },
    // 12 - TextBindingOpt: Ws^ /* Clipped */;
    Production {
        lhs: 56,
        production: &[ParseType::N(63)],
    },
    // 13 - TextBindingOpt: ;
    Production {
        lhs: 56,
        production: &[],
    },
    // 14 - Section: At Keys SectionList /* Vec */;
    Production {
        lhs: 45,
        production: &[ParseType::N(47), ParseType::N(34), ParseType::N(7)],
    },
    // 15 - SectionList: Binding SectionList;
    Production {
        lhs: 47,
        production: &[ParseType::N(47), ParseType::N(10)],
    },
    // 16 - SectionList: ;
    Production {
        lhs: 47,
        production: &[],
    },
    // 17 - Keys: Key KeysList /* Vec */;
    Production {
        lhs: 34,
        production: &[ParseType::N(35), ParseType::N(31)],
    },
    // 18 - KeysList: Dot Key KeysList;
    Production {
        lhs: 35,
        production: &[ParseType::N(35), ParseType::N(31), ParseType::N(22)],
    },
    // 19 - KeysList: ;
    Production {
        lhs: 35,
        production: &[],
    },
    // 20 - Key: KeyBase KeyOpt /* Option */;
    Production {
        lhs: 31,
        production: &[ParseType::N(33), ParseType::N(32)],
    },
    // 21 - KeyOpt: ArrayMarker;
    Production {
        lhs: 33,
        production: &[ParseType::N(4)],
    },
    // 22 - KeyOpt: ;
    Production {
        lhs: 33,
        production: &[],
    },
    // 23 - ArrayMarker: ArrayBegin ArrayMarkerOpt /* Option */ ArrayEnd;
    Production {
        lhs: 4,
        production: &[ParseType::N(2), ParseType::N(5), ParseType::N(1)],
    },
    // 24 - ArrayMarkerOpt: Integer;
    Production {
        lhs: 5,
        production: &[ParseType::N(30)],
    },
    // 25 - ArrayMarkerOpt: ;
    Production {
        lhs: 5,
        production: &[],
    },
    // 26 - KeyBase: Ident;
    Production {
        lhs: 32,
        production: &[ParseType::N(28)],
    },
    // 27 - KeyBase: ExtensionNameSpace;
    Production {
        lhs: 32,
        production: &[ParseType::N(25)],
    },
    // 28 - KeyBase: Str;
    Production {
        lhs: 32,
        production: &[ParseType::N(48)],
    },
    // 29 - KeyBase: Integer;
    Production {
        lhs: 32,
        production: &[ParseType::N(30)],
    },
    // 30 - ExtensionNameSpace: Ext Ident;
    Production {
        lhs: 25,
        production: &[ParseType::N(28), ParseType::N(24)],
    },
    // 31 - Value: Object;
    Production {
        lhs: 61,
        production: &[ParseType::N(41)],
    },
    // 32 - Value: Array;
    Production {
        lhs: 61,
        production: &[ParseType::N(0)],
    },
    // 33 - Value: Integer;
    Production {
        lhs: 61,
        production: &[ParseType::N(30)],
    },
    // 34 - Value: Boolean;
    Production {
        lhs: 61,
        production: &[ParseType::N(12)],
    },
    // 35 - Value: Null;
    Production {
        lhs: 61,
        production: &[ParseType::N(40)],
    },
    // 36 - Value: StrContinues;
    Production {
        lhs: 61,
        production: &[ParseType::N(49)],
    },
    // 37 - Value: TypedStr;
    Production {
        lhs: 61,
        production: &[ParseType::N(60)],
    },
    // 38 - Value: Hole;
    Production {
        lhs: 61,
        production: &[ParseType::N(27)],
    },
    // 39 - Value: NamedCodeBlock;
    Production {
        lhs: 61,
        production: &[ParseType::N(37)],
    },
    // 40 - Value: CodeBlock;
    Production {
        lhs: 61,
        production: &[ParseType::N(14)],
    },
    // 41 - Value: NamedCode;
    Production {
        lhs: 61,
        production: &[ParseType::N(36)],
    },
    // 42 - Value: Code;
    Production {
        lhs: 61,
        production: &[ParseType::N(13)],
    },
    // 43 - Object: Begin ObjectList /* Vec */ End;
    Production {
        lhs: 41,
        production: &[ParseType::N(23), ParseType::N(42), ParseType::N(8)],
    },
    // 44 - ObjectList: Key Bind Value ObjectOpt /* Option */ ObjectList;
    Production {
        lhs: 42,
        production: &[
            ParseType::N(42),
            ParseType::N(43),
            ParseType::N(61),
            ParseType::N(9),
            ParseType::N(31),
        ],
    },
    // 45 - ObjectList: ;
    Production {
        lhs: 42,
        production: &[],
    },
    // 46 - ObjectOpt: Comma;
    Production {
        lhs: 43,
        production: &[ParseType::N(20)],
    },
    // 47 - ObjectOpt: ;
    Production {
        lhs: 43,
        production: &[],
    },
    // 48 - Array: ArrayBegin ArrayList /* Vec */ ArrayEnd;
    Production {
        lhs: 0,
        production: &[ParseType::N(2), ParseType::N(3), ParseType::N(1)],
    },
    // 49 - ArrayList: Value ArrayOpt /* Option */ ArrayList;
    Production {
        lhs: 3,
        production: &[ParseType::N(3), ParseType::N(6), ParseType::N(61)],
    },
    // 50 - ArrayList: ;
    Production {
        lhs: 3,
        production: &[],
    },
    // 51 - ArrayOpt: Comma;
    Production {
        lhs: 6,
        production: &[ParseType::N(20)],
    },
    // 52 - ArrayOpt: ;
    Production {
        lhs: 6,
        production: &[],
    },
    // 53 - Integer: /\d[\d_]*/;
    Production {
        lhs: 30,
        production: &[ParseType::T(5)],
    },
    // 54 - Boolean: True;
    Production {
        lhs: 12,
        production: &[ParseType::N(58)],
    },
    // 55 - Boolean: False;
    Production {
        lhs: 12,
        production: &[ParseType::N(26)],
    },
    // 56 - True: 'true';
    Production {
        lhs: 58,
        production: &[ParseType::T(6)],
    },
    // 57 - False: 'false';
    Production {
        lhs: 26,
        production: &[ParseType::T(7)],
    },
    // 58 - Null: 'null';
    Production {
        lhs: 40,
        production: &[ParseType::T(8)],
    },
    // 59 - Hole: '!';
    Production {
        lhs: 27,
        production: &[ParseType::T(9)],
    },
    // 60 - StrContinues: Str StrContinuesList /* Vec */;
    Production {
        lhs: 49,
        production: &[ParseType::N(50), ParseType::N(48)],
    },
    // 61 - StrContinuesList: Continue Str StrContinuesList;
    Production {
        lhs: 50,
        production: &[ParseType::N(50), ParseType::N(48), ParseType::N(21)],
    },
    // 62 - StrContinuesList: ;
    Production {
        lhs: 50,
        production: &[],
    },
    // 63 - Str: Quote InStr Quote;
    Production {
        lhs: 48,
        production: &[ParseType::N(44), ParseType::N(29), ParseType::N(44)],
    },
    // 64 - TypedStr: TypedQuote InStr Quote;
    Production {
        lhs: 60,
        production: &[ParseType::N(44), ParseType::N(29), ParseType::N(59)],
    },
    // 65 - Quote: '"';
    Production {
        lhs: 44,
        production: &[ParseType::T(10)],
    },
    // 66 - TypedQuote: /[a-zA-Z0-9-_]+"/;
    Production {
        lhs: 59,
        production: &[ParseType::T(11)],
    },
    // 67 - InStr: /(\\[nrt\\"0]|[^\\"\r\n])*/;
    Production {
        lhs: 29,
        production: &[ParseType::T(12)],
    },
    // 68 - Text: /[^\\"\r\n]*/;
    Production {
        lhs: 54,
        production: &[ParseType::T(13)],
    },
    // 69 - NamedCodeBlock: NamedCodeBlockBegin CodeBlockTailCommon;
    Production {
        lhs: 37,
        production: &[ParseType::N(17), ParseType::N(38)],
    },
    // 70 - CodeBlock: CodeBlockDelimiter CodeBlockTailCommon;
    Production {
        lhs: 14,
        production: &[ParseType::N(17), ParseType::N(15)],
    },
    // 71 - CodeBlockTailCommon: Newline CodeBlockTailCommonList /* Vec */ CodeBlockTailCommonOpt /* Option */ CodeBlockDelimiter;
    Production {
        lhs: 17,
        production: &[
            ParseType::N(15),
            ParseType::N(19),
            ParseType::N(18),
            ParseType::N(39),
        ],
    },
    // 72 - CodeBlockTailCommonList: CodeBlockLine Newline CodeBlockTailCommonList;
    Production {
        lhs: 18,
        production: &[ParseType::N(18), ParseType::N(39), ParseType::N(16)],
    },
    // 73 - CodeBlockTailCommonList: ;
    Production {
        lhs: 18,
        production: &[],
    },
    // 74 - CodeBlockTailCommonOpt: Ws;
    Production {
        lhs: 19,
        production: &[ParseType::N(63)],
    },
    // 75 - CodeBlockTailCommonOpt: ;
    Production {
        lhs: 19,
        production: &[],
    },
    // 76 - NamedCode: /[a-zA-Z0-9-_]+`([^`\r\n]|\\`)*`/;
    Production {
        lhs: 36,
        production: &[ParseType::T(14)],
    },
    // 77 - Code: /`([^`\r\n]|\\`)*`/;
    Production {
        lhs: 13,
        production: &[ParseType::T(15)],
    },
    // 78 - Newline: /\r\n|\r|\n/;
    Production {
        lhs: 39,
        production: &[ParseType::T(16)],
    },
    // 79 - Ws: /[\s--\r\n]+/;
    Production {
        lhs: 63,
        production: &[ParseType::T(17)],
    },
    // 80 - At: '@';
    Production {
        lhs: 7,
        production: &[ParseType::T(18)],
    },
    // 81 - Ext: '$';
    Production {
        lhs: 24,
        production: &[ParseType::T(19)],
    },
    // 82 - Dot: '.';
    Production {
        lhs: 22,
        production: &[ParseType::T(20)],
    },
    // 83 - Begin: '{';
    Production {
        lhs: 8,
        production: &[ParseType::T(21)],
    },
    // 84 - End: '}';
    Production {
        lhs: 23,
        production: &[ParseType::T(22)],
    },
    // 85 - ArrayBegin: '[';
    Production {
        lhs: 1,
        production: &[ParseType::T(23)],
    },
    // 86 - ArrayEnd: ']';
    Production {
        lhs: 2,
        production: &[ParseType::T(24)],
    },
    // 87 - Bind: '=';
    Production {
        lhs: 9,
        production: &[ParseType::T(25)],
    },
    // 88 - Comma: ',';
    Production {
        lhs: 20,
        production: &[ParseType::T(26)],
    },
    // 89 - Continue: '\\';
    Production {
        lhs: 21,
        production: &[ParseType::T(27)],
    },
    // 90 - TextStart: ":";
    Production {
        lhs: 57,
        production: &[ParseType::T(28)],
    },
    // 91 - Ident: /[a-zA-Z_\-0-9]+/;
    Production {
        lhs: 28,
        production: &[ParseType::T(29)],
    },
    // 92 - NamedCodeBlockBegin: /```[a-zA-Z0-9-_]+/;
    Production {
        lhs: 38,
        production: &[ParseType::T(30)],
    },
    // 93 - CodeBlockDelimiter: /```/;
    Production {
        lhs: 15,
        production: &[ParseType::T(31)],
    },
    // 94 - CodeBlockLine: /[^\n]*/;
    Production {
        lhs: 16,
        production: &[ParseType::T(32)],
    },
];

static SCANNERS: Lazy<Vec<ScannerConfig>> = Lazy::new(|| {
    vec![
        ScannerConfig::new(
            "INITIAL",
            Tokenizer::build(TERMINALS, SCANNER_0.0, SCANNER_0.1).unwrap(),
            &[
                (10 /* Quote */, 1 /* Str */),
                (11 /* TypedQuote */, 1 /* Str */),
                (28 /* TextStart */, 3 /* Text */),
                (
                    30, /* NamedCodeBlockBegin */
                    2,  /* CodeBlockState */
                ),
                (
                    31, /* CodeBlockDelimiter */
                    2,  /* CodeBlockState */
                ),
            ],
        ),
        ScannerConfig::new(
            "Str",
            Tokenizer::build(TERMINALS, SCANNER_1.0, SCANNER_1.1).unwrap(),
            &[(10 /* Quote */, 0 /* INITIAL */)],
        ),
        ScannerConfig::new(
            "CodeBlockState",
            Tokenizer::build(TERMINALS, SCANNER_2.0, SCANNER_2.1).unwrap(),
            &[(31 /* CodeBlockDelimiter */, 0 /* INITIAL */)],
        ),
        ScannerConfig::new(
            "Text",
            Tokenizer::build(TERMINALS, SCANNER_3.0, SCANNER_3.1).unwrap(),
            &[(16 /* Newline */, 0 /* INITIAL */)],
        ),
    ]
});

pub fn parse<'t, T>(
    input: &'t str,
    file_name: T,
    user_actions: &mut Grammar<'t>,
) -> Result<ParseTree, ParolError>
where
    T: AsRef<Path>,
{
    use parol_runtime::parser::parse_tree_type::SynTree;
    use parol_runtime::parser::parser_types::SynTreeFlavor;
    use parol_runtime::syntree::Builder;
    let mut builder = Builder::<SynTree, SynTreeFlavor>::new_with();
    parse_into(input, &mut builder, file_name, user_actions)?;
    Ok(builder.build()?)
}
#[allow(dead_code)]
pub fn parse_into<'t, T: TreeConstruct<'t>>(
    input: &'t str,
    tree_builder: &mut T,
    file_name: impl AsRef<Path>,
    user_actions: &mut Grammar<'t>,
) -> Result<(), ParolError>
where
    ParolError: From<T::Error>,
{
    let mut llk_parser = LLKParser::new(
        51,
        LOOKAHEAD_AUTOMATA,
        PRODUCTIONS,
        TERMINAL_NAMES,
        NON_TERMINALS,
    );
    // Initialize wrapper
    let mut user_actions = GrammarAuto::new(user_actions);
    llk_parser.parse_into::<T>(
        tree_builder,
        TokenStream::new(input, file_name, &SCANNERS, MAX_K).unwrap(),
        &mut user_actions,
    )
}
